// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tmcs_msg.proto

package tmcs_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_None            ErrorCode = 0
	ErrorCode_InvalidMessage  ErrorCode = 1000
	ErrorCode_VerifyError     ErrorCode = 1001
	ErrorCode_ReceiverUnknown ErrorCode = 1002
	ErrorCode_InvalidKey      ErrorCode = 1003
)

var ErrorCode_name = map[int32]string{
	0:    "None",
	1000: "InvalidMessage",
	1001: "VerifyError",
	1002: "ReceiverUnknown",
	1003: "InvalidKey",
}

var ErrorCode_value = map[string]int32{
	"None":            0,
	"InvalidMessage":  1000,
	"VerifyError":     1001,
	"ReceiverUnknown": 1002,
	"InvalidKey":      1003,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{0}
}

type SignedMsg_Type int32

const (
	SignedMsg_Message SignedMsg_Type = 0
	SignedMsg_Receipt SignedMsg_Type = 1
	SignedMsg_Error   SignedMsg_Type = 2
)

var SignedMsg_Type_name = map[int32]string{
	0: "Message",
	1: "Receipt",
	2: "Error",
}

var SignedMsg_Type_value = map[string]int32{
	"Message": 0,
	"Receipt": 1,
	"Error":   2,
}

func (x SignedMsg_Type) String() string {
	return proto.EnumName(SignedMsg_Type_name, int32(x))
}

func (SignedMsg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{1, 0}
}

type MsgReceipt_MsgState int32

const (
	MsgReceipt_Lost         MsgReceipt_MsgState = 0
	MsgReceipt_Received     MsgReceipt_MsgState = 1
	MsgReceipt_Timeout      MsgReceipt_MsgState = 2
	MsgReceipt_VerifyFailed MsgReceipt_MsgState = 4
)

var MsgReceipt_MsgState_name = map[int32]string{
	0: "Lost",
	1: "Received",
	2: "Timeout",
	4: "VerifyFailed",
}

var MsgReceipt_MsgState_value = map[string]int32{
	"Lost":         0,
	"Received":     1,
	"Timeout":      2,
	"VerifyFailed": 4,
}

func (x MsgReceipt_MsgState) String() string {
	return proto.EnumName(MsgReceipt_MsgState_name, int32(x))
}

func (MsgReceipt_MsgState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{6, 0}
}

type NewSession struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	LifeTime             int64    `protobuf:"varint,2,opt,name=lifeTime,proto3" json:"lifeTime,omitempty"`
	Group                bool     `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSession) Reset()         { *m = NewSession{} }
func (m *NewSession) String() string { return proto.CompactTextString(m) }
func (*NewSession) ProtoMessage()    {}
func (*NewSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{0}
}

func (m *NewSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSession.Unmarshal(m, b)
}
func (m *NewSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSession.Marshal(b, m, deterministic)
}
func (m *NewSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSession.Merge(m, src)
}
func (m *NewSession) XXX_Size() int {
	return xxx_messageInfo_NewSession.Size(m)
}
func (m *NewSession) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSession.DiscardUnknown(m)
}

var xxx_messageInfo_NewSession proto.InternalMessageInfo

func (m *NewSession) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *NewSession) GetLifeTime() int64 {
	if m != nil {
		return m.LifeTime
	}
	return 0
}

func (m *NewSession) GetGroup() bool {
	if m != nil {
		return m.Group
	}
	return false
}

type SignedMsg struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 SignedMsg_Type `protobuf:"varint,2,opt,name=type,proto3,enum=tmcs_msg.SignedMsg_Type" json:"type,omitempty"`
	Receiver             string         `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender               string         `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Body                 []byte         `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Sign                 []byte         `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignedMsg) Reset()         { *m = SignedMsg{} }
func (m *SignedMsg) String() string { return proto.CompactTextString(m) }
func (*SignedMsg) ProtoMessage()    {}
func (*SignedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{1}
}

func (m *SignedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMsg.Unmarshal(m, b)
}
func (m *SignedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMsg.Marshal(b, m, deterministic)
}
func (m *SignedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMsg.Merge(m, src)
}
func (m *SignedMsg) XXX_Size() int {
	return xxx_messageInfo_SignedMsg.Size(m)
}
func (m *SignedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMsg proto.InternalMessageInfo

func (m *SignedMsg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SignedMsg) GetType() SignedMsg_Type {
	if m != nil {
		return m.Type
	}
	return SignedMsg_Message
}

func (m *SignedMsg) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *SignedMsg) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SignedMsg) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *SignedMsg) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type MessagePack struct {
	Msg                  []*Message `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessagePack) Reset()         { *m = MessagePack{} }
func (m *MessagePack) String() string { return proto.CompactTextString(m) }
func (*MessagePack) ProtoMessage()    {}
func (*MessagePack) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{2}
}

func (m *MessagePack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePack.Unmarshal(m, b)
}
func (m *MessagePack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePack.Marshal(b, m, deterministic)
}
func (m *MessagePack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePack.Merge(m, src)
}
func (m *MessagePack) XXX_Size() int {
	return xxx_messageInfo_MessagePack.Size(m)
}
func (m *MessagePack) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePack.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePack proto.InternalMessageInfo

func (m *MessagePack) GetMsg() []*Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MsgPackage struct {
	Receipts             []*MsgReceipt `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	Messages             []*Message    `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgPackage) Reset()         { *m = MsgPackage{} }
func (m *MsgPackage) String() string { return proto.CompactTextString(m) }
func (*MsgPackage) ProtoMessage()    {}
func (*MsgPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{3}
}

func (m *MsgPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPackage.Unmarshal(m, b)
}
func (m *MsgPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPackage.Marshal(b, m, deterministic)
}
func (m *MsgPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPackage.Merge(m, src)
}
func (m *MsgPackage) XXX_Size() int {
	return xxx_messageInfo_MsgPackage.Size(m)
}
func (m *MsgPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPackage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPackage proto.InternalMessageInfo

func (m *MsgPackage) GetReceipts() []*MsgReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func (m *MsgPackage) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	MsgId string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// PGP fingerprint of receiver
	Receiver  string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Message body encrypted with sender's private key
	EncryptedMsg         []byte   `protobuf:"bytes,4,opt,name=encryptedMsg,proto3" json:"encryptedMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *Message) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetEncryptedMsg() []byte {
	if m != nil {
		return m.EncryptedMsg
	}
	return nil
}

type ReceiptPack struct {
	Receipts             []*MsgReceipt `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReceiptPack) Reset()         { *m = ReceiptPack{} }
func (m *ReceiptPack) String() string { return proto.CompactTextString(m) }
func (*ReceiptPack) ProtoMessage()    {}
func (*ReceiptPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{5}
}

func (m *ReceiptPack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptPack.Unmarshal(m, b)
}
func (m *ReceiptPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptPack.Marshal(b, m, deterministic)
}
func (m *ReceiptPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptPack.Merge(m, src)
}
func (m *ReceiptPack) XXX_Size() int {
	return xxx_messageInfo_ReceiptPack.Size(m)
}
func (m *ReceiptPack) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptPack.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptPack proto.InternalMessageInfo

func (m *ReceiptPack) GetReceipts() []*MsgReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

type MsgReceipt struct {
	MsgId                string              `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	State                MsgReceipt_MsgState `protobuf:"varint,2,opt,name=state,proto3,enum=tmcs_msg.MsgReceipt_MsgState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MsgReceipt) Reset()         { *m = MsgReceipt{} }
func (m *MsgReceipt) String() string { return proto.CompactTextString(m) }
func (*MsgReceipt) ProtoMessage()    {}
func (*MsgReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{6}
}

func (m *MsgReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReceipt.Unmarshal(m, b)
}
func (m *MsgReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReceipt.Marshal(b, m, deterministic)
}
func (m *MsgReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReceipt.Merge(m, src)
}
func (m *MsgReceipt) XXX_Size() int {
	return xxx_messageInfo_MsgReceipt.Size(m)
}
func (m *MsgReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReceipt proto.InternalMessageInfo

func (m *MsgReceipt) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *MsgReceipt) GetState() MsgReceipt_MsgState {
	if m != nil {
		return m.State
	}
	return MsgReceipt_Lost
}

type Error struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=tmcs_msg.ErrorCode" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{7}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_None
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ClientHandShake struct {
	ClientVersion        int32    `protobuf:"varint,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHandShake) Reset()         { *m = ClientHandShake{} }
func (m *ClientHandShake) String() string { return proto.CompactTextString(m) }
func (*ClientHandShake) ProtoMessage()    {}
func (*ClientHandShake) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{8}
}

func (m *ClientHandShake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHandShake.Unmarshal(m, b)
}
func (m *ClientHandShake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHandShake.Marshal(b, m, deterministic)
}
func (m *ClientHandShake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHandShake.Merge(m, src)
}
func (m *ClientHandShake) XXX_Size() int {
	return xxx_messageInfo_ClientHandShake.Size(m)
}
func (m *ClientHandShake) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHandShake.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHandShake proto.InternalMessageInfo

func (m *ClientHandShake) GetClientVersion() int32 {
	if m != nil {
		return m.ClientVersion
	}
	return 0
}

type ServerHandShake struct {
	ServerVersion        int32    `protobuf:"varint,1,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerHandShake) Reset()         { *m = ServerHandShake{} }
func (m *ServerHandShake) String() string { return proto.CompactTextString(m) }
func (*ServerHandShake) ProtoMessage()    {}
func (*ServerHandShake) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{9}
}

func (m *ServerHandShake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerHandShake.Unmarshal(m, b)
}
func (m *ServerHandShake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerHandShake.Marshal(b, m, deterministic)
}
func (m *ServerHandShake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerHandShake.Merge(m, src)
}
func (m *ServerHandShake) XXX_Size() int {
	return xxx_messageInfo_ServerHandShake.Size(m)
}
func (m *ServerHandShake) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerHandShake.DiscardUnknown(m)
}

var xxx_messageInfo_ServerHandShake proto.InternalMessageInfo

func (m *ServerHandShake) GetServerVersion() int32 {
	if m != nil {
		return m.ServerVersion
	}
	return 0
}

func (m *ServerHandShake) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SignIn struct {
	FingerPrint          string   `protobuf:"bytes,1,opt,name=fingerPrint,proto3" json:"fingerPrint,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignIn) Reset()         { *m = SignIn{} }
func (m *SignIn) String() string { return proto.CompactTextString(m) }
func (*SignIn) ProtoMessage()    {}
func (*SignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{10}
}

func (m *SignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignIn.Unmarshal(m, b)
}
func (m *SignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignIn.Marshal(b, m, deterministic)
}
func (m *SignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignIn.Merge(m, src)
}
func (m *SignIn) XXX_Size() int {
	return xxx_messageInfo_SignIn.Size(m)
}
func (m *SignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SignIn.DiscardUnknown(m)
}

var xxx_messageInfo_SignIn proto.InternalMessageInfo

func (m *SignIn) GetFingerPrint() string {
	if m != nil {
		return m.FingerPrint
	}
	return ""
}

func (m *SignIn) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SignIn) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterEnum("tmcs_msg.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("tmcs_msg.SignedMsg_Type", SignedMsg_Type_name, SignedMsg_Type_value)
	proto.RegisterEnum("tmcs_msg.MsgReceipt_MsgState", MsgReceipt_MsgState_name, MsgReceipt_MsgState_value)
	proto.RegisterType((*NewSession)(nil), "tmcs_msg.NewSession")
	proto.RegisterType((*SignedMsg)(nil), "tmcs_msg.SignedMsg")
	proto.RegisterType((*MessagePack)(nil), "tmcs_msg.MessagePack")
	proto.RegisterType((*MsgPackage)(nil), "tmcs_msg.MsgPackage")
	proto.RegisterType((*Message)(nil), "tmcs_msg.Message")
	proto.RegisterType((*ReceiptPack)(nil), "tmcs_msg.ReceiptPack")
	proto.RegisterType((*MsgReceipt)(nil), "tmcs_msg.MsgReceipt")
	proto.RegisterType((*Error)(nil), "tmcs_msg.Error")
	proto.RegisterType((*ClientHandShake)(nil), "tmcs_msg.ClientHandShake")
	proto.RegisterType((*ServerHandShake)(nil), "tmcs_msg.ServerHandShake")
	proto.RegisterType((*SignIn)(nil), "tmcs_msg.SignIn")
}

func init() { proto.RegisterFile("tmcs_msg.proto", fileDescriptor_9c7e6332a77e25ed) }

var fileDescriptor_9c7e6332a77e25ed = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x25, 0x89, 0x93, 0x38, 0x37, 0x21, 0x31, 0xd3, 0x0a, 0x59, 0x08, 0xa4, 0x6a, 0x40, 0xa2,
	0xe2, 0x51, 0xa1, 0x74, 0xc1, 0x12, 0xa1, 0x0a, 0x44, 0x05, 0xad, 0xaa, 0x49, 0xe9, 0x12, 0xe4,
	0xda, 0x53, 0x63, 0x25, 0x19, 0x5b, 0x33, 0xd3, 0x56, 0x59, 0xf0, 0x23, 0x7c, 0x16, 0x5f, 0xc1,
	0xe3, 0x27, 0xb8, 0xf3, 0x88, 0xd3, 0x54, 0xed, 0x82, 0x9d, 0xef, 0xb9, 0xef, 0x73, 0xe6, 0x1a,
	0x86, 0x7a, 0x9e, 0xaa, 0xaf, 0x73, 0x95, 0xef, 0x54, 0xb2, 0xd4, 0x25, 0x09, 0x97, 0x36, 0x3d,
	0x01, 0x38, 0xe4, 0x97, 0x13, 0xae, 0x54, 0x51, 0x0a, 0x72, 0x1f, 0x3a, 0xd5, 0xf9, 0xe9, 0x94,
	0x2f, 0xe2, 0xc6, 0x56, 0x63, 0xbb, 0xc7, 0xbc, 0x45, 0x1e, 0x40, 0x38, 0x2b, 0xce, 0xf8, 0x71,
	0x31, 0xe7, 0x71, 0x13, 0x3d, 0x2d, 0x56, 0xdb, 0x64, 0x13, 0xda, 0xb9, 0x2c, 0xcf, 0xab, 0xb8,
	0x85, 0x8e, 0x90, 0x39, 0x83, 0xfe, 0x6c, 0x40, 0x6f, 0x52, 0xe4, 0x82, 0x67, 0x07, 0x2a, 0x27,
	0x43, 0x68, 0x16, 0x99, 0xad, 0xd9, 0x66, 0xf8, 0x45, 0x5e, 0x40, 0xa0, 0x17, 0x95, 0xab, 0x35,
	0x1c, 0xc7, 0x3b, 0xf5, 0x78, 0x75, 0xca, 0xce, 0x31, 0xfa, 0x99, 0x8d, 0x32, 0xdd, 0x25, 0x4f,
	0x79, 0x71, 0xc1, 0xa5, 0x6d, 0xd2, 0x63, 0xb5, 0x6d, 0x26, 0x56, 0x5c, 0x64, 0xe8, 0x09, 0xdc,
	0xc4, 0xce, 0x22, 0x04, 0x82, 0xd3, 0x32, 0x5b, 0xc4, 0x6d, 0x44, 0x07, 0xcc, 0x7e, 0x1b, 0x4c,
	0x61, 0xfd, 0xb8, 0xe3, 0x30, 0xf3, 0x4d, 0x9f, 0x43, 0x60, 0x3a, 0x91, 0x3e, 0x74, 0x0f, 0x90,
	0x84, 0x24, 0xe7, 0xd1, 0x1d, 0x63, 0x30, 0xd3, 0xa0, 0xd2, 0x51, 0x83, 0xf4, 0xa0, 0xfd, 0x4e,
	0xca, 0x52, 0x46, 0x4d, 0x3a, 0x86, 0xbe, 0x0f, 0x3a, 0x4a, 0xd2, 0x29, 0x79, 0x0c, 0x2d, 0x9c,
	0x19, 0xd7, 0x6a, 0x6d, 0xf7, 0xc7, 0xf7, 0x56, 0x4b, 0xf8, 0x18, 0x66, 0xbc, 0x74, 0x0e, 0x80,
	0xeb, 0x98, 0x78, 0x84, 0xc8, 0x2b, 0xbf, 0x4a, 0xa5, 0x95, 0xcf, 0xdb, 0xbc, 0x92, 0xa7, 0x72,
	0xdf, 0x96, 0xd5, 0x51, 0xe4, 0x25, 0x84, 0x73, 0x57, 0x4f, 0x21, 0x5d, 0xb7, 0x74, 0xaa, 0x43,
	0xe8, 0xf7, 0x7a, 0x0f, 0x23, 0x0c, 0xc6, 0xec, 0x67, 0x5e, 0x4b, 0x67, 0xac, 0x91, 0xd9, 0xbc,
	0x46, 0xe6, 0x43, 0xe8, 0x69, 0x94, 0x54, 0xe9, 0x64, 0xee, 0xe4, 0x6c, 0xb1, 0x15, 0x40, 0x28,
	0x0c, 0xb8, 0x48, 0xe5, 0xa2, 0xd2, 0x56, 0x21, 0x4b, 0xf8, 0x80, 0xad, 0x61, 0xf4, 0x0d, 0xf4,
	0xfd, 0x0a, 0x96, 0xa1, 0xff, 0x5e, 0x97, 0xfe, 0x68, 0x58, 0xbe, 0xbc, 0xe3, 0x96, 0x1d, 0x76,
	0xa1, 0x8d, 0x23, 0xe9, 0xe5, 0xfb, 0x79, 0x74, 0x53, 0x4d, 0xf3, 0x39, 0x31, 0x41, 0xcc, 0xc5,
	0xd2, 0xb7, 0x10, 0x2e, 0x21, 0x12, 0x42, 0xf0, 0xa9, 0x54, 0x1a, 0xa5, 0x1e, 0x40, 0xc8, 0xdc,
	0xfa, 0x19, 0x6a, 0x8d, 0xc2, 0x9b, 0x37, 0x5d, 0x9e, 0xeb, 0xa8, 0x49, 0x22, 0x18, 0x9c, 0x70,
	0x59, 0x9c, 0x2d, 0xde, 0x27, 0xc5, 0x0c, 0xdd, 0x01, 0xfd, 0xe2, 0x9f, 0x02, 0x79, 0x0a, 0x41,
	0x5a, 0x66, 0xdc, 0x4e, 0x35, 0x1c, 0x6f, 0xac, 0xfa, 0x5b, 0xf7, 0x1e, 0xba, 0x98, 0x0d, 0x20,
	0x31, 0x74, 0xbd, 0x34, 0x9e, 0xec, 0xa5, 0x69, 0x1e, 0x63, 0x96, 0xe8, 0xc4, 0x3f, 0x68, 0xfb,
	0x4d, 0x5f, 0xc3, 0x68, 0x6f, 0x56, 0x70, 0xa1, 0x3f, 0x24, 0x22, 0x9b, 0x7c, 0x4b, 0xa6, 0x9c,
	0x3c, 0x81, 0xbb, 0xa9, 0x85, 0x70, 0x14, 0x73, 0xa2, 0xfe, 0x88, 0xd6, 0x41, 0x7a, 0x00, 0xa3,
	0x09, 0x97, 0x28, 0xe1, 0x5a, 0xa2, 0xb2, 0xd0, 0xb5, 0xc4, 0x35, 0xd0, 0xf0, 0xab, 0xcb, 0x29,
	0x17, 0x7e, 0x3a, 0x67, 0xd0, 0x63, 0xe8, 0x98, 0x43, 0xdc, 0x17, 0x64, 0x0b, 0xfa, 0x67, 0x85,
	0xc8, 0xb9, 0x3c, 0x92, 0x85, 0xd0, 0x5e, 0x85, 0xab, 0xd0, 0xcd, 0x15, 0xea, 0x53, 0x6b, 0xad,
	0x4e, 0xed, 0x59, 0x0a, 0xbd, 0x9a, 0x1e, 0xa3, 0xc0, 0x61, 0x29, 0xcc, 0xb1, 0x6d, 0xc0, 0x70,
	0x5f, 0x5c, 0x24, 0xb3, 0x22, 0x5b, 0x1e, 0xe0, 0xaf, 0x2e, 0x72, 0xdf, 0x77, 0xdc, 0xbb, 0xd3,
	0xfb, 0xdd, 0xc5, 0x3e, 0x23, 0x2f, 0x94, 0xfc, 0x2c, 0xa6, 0xa2, 0xbc, 0x14, 0xd1, 0x9f, 0x2e,
	0x19, 0x01, 0xf8, 0xe4, 0x8f, 0x7c, 0x11, 0xfd, 0xed, 0x9e, 0x76, 0xec, 0x0f, 0x6e, 0xf7, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0x12, 0xce, 0xab, 0xf2, 0x04, 0x00, 0x00,
}
