// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tmcs_msg.proto

package tmcs_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignedMsg_MsgType int32

const (
	SignedMsg_Message SignedMsg_MsgType = 0
	SignedMsg_Receipt SignedMsg_MsgType = 1
)

var SignedMsg_MsgType_name = map[int32]string{
	0: "Message",
	1: "Receipt",
}

var SignedMsg_MsgType_value = map[string]int32{
	"Message": 0,
	"Receipt": 1,
}

func (x SignedMsg_MsgType) String() string {
	return proto.EnumName(SignedMsg_MsgType_name, int32(x))
}

func (SignedMsg_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{1, 0}
}

type MsgReceipt_MsgState int32

const (
	MsgReceipt_Lost     MsgReceipt_MsgState = 0
	MsgReceipt_Received MsgReceipt_MsgState = 1
	MsgReceipt_Timeout  MsgReceipt_MsgState = 2
)

var MsgReceipt_MsgState_name = map[int32]string{
	0: "Lost",
	1: "Received",
	2: "Timeout",
}

var MsgReceipt_MsgState_value = map[string]int32{
	"Lost":     0,
	"Received": 1,
	"Timeout":  2,
}

func (x MsgReceipt_MsgState) String() string {
	return proto.EnumName(MsgReceipt_MsgState_name, int32(x))
}

func (MsgReceipt_MsgState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{6, 0}
}

type NewSession struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	LifeTime             int64    `protobuf:"varint,2,opt,name=lifeTime,proto3" json:"lifeTime,omitempty"`
	Group                bool     `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSession) Reset()         { *m = NewSession{} }
func (m *NewSession) String() string { return proto.CompactTextString(m) }
func (*NewSession) ProtoMessage()    {}
func (*NewSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{0}
}

func (m *NewSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSession.Unmarshal(m, b)
}
func (m *NewSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSession.Marshal(b, m, deterministic)
}
func (m *NewSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSession.Merge(m, src)
}
func (m *NewSession) XXX_Size() int {
	return xxx_messageInfo_NewSession.Size(m)
}
func (m *NewSession) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSession.DiscardUnknown(m)
}

var xxx_messageInfo_NewSession proto.InternalMessageInfo

func (m *NewSession) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *NewSession) GetLifeTime() int64 {
	if m != nil {
		return m.LifeTime
	}
	return 0
}

func (m *NewSession) GetGroup() bool {
	if m != nil {
		return m.Group
	}
	return false
}

type SignedMsg struct {
	// Protobuf binary of {MsgPackage}, not encrypted
	Message     []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FingerPrint string `protobuf:"bytes,2,opt,name=fingerPrint,proto3" json:"fingerPrint,omitempty"`
	Sender      string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	// Signature of message binary
	Sign                 string            `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	Type                 SignedMsg_MsgType `protobuf:"varint,5,opt,name=type,proto3,enum=tmcs_msg.SignedMsg_MsgType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SignedMsg) Reset()         { *m = SignedMsg{} }
func (m *SignedMsg) String() string { return proto.CompactTextString(m) }
func (*SignedMsg) ProtoMessage()    {}
func (*SignedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{1}
}

func (m *SignedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMsg.Unmarshal(m, b)
}
func (m *SignedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMsg.Marshal(b, m, deterministic)
}
func (m *SignedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMsg.Merge(m, src)
}
func (m *SignedMsg) XXX_Size() int {
	return xxx_messageInfo_SignedMsg.Size(m)
}
func (m *SignedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMsg proto.InternalMessageInfo

func (m *SignedMsg) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMsg) GetFingerPrint() string {
	if m != nil {
		return m.FingerPrint
	}
	return ""
}

func (m *SignedMsg) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SignedMsg) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *SignedMsg) GetType() SignedMsg_MsgType {
	if m != nil {
		return m.Type
	}
	return SignedMsg_Message
}

type MsgPackage struct {
	Receipts             []*MsgReceipt `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	Messages             []*Message    `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MsgPackage) Reset()         { *m = MsgPackage{} }
func (m *MsgPackage) String() string { return proto.CompactTextString(m) }
func (*MsgPackage) ProtoMessage()    {}
func (*MsgPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{2}
}

func (m *MsgPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPackage.Unmarshal(m, b)
}
func (m *MsgPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPackage.Marshal(b, m, deterministic)
}
func (m *MsgPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPackage.Merge(m, src)
}
func (m *MsgPackage) XXX_Size() int {
	return xxx_messageInfo_MsgPackage.Size(m)
}
func (m *MsgPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPackage.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPackage proto.InternalMessageInfo

func (m *MsgPackage) GetReceipts() []*MsgReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func (m *MsgPackage) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	MsgId string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// PGP fingerprint of receiver
	Receiver string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// Message body encrypted with sender's private key
	EncryptedMsg         []byte   `protobuf:"bytes,3,opt,name=encryptedMsg,proto3" json:"encryptedMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *Message) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Message) GetEncryptedMsg() []byte {
	if m != nil {
		return m.EncryptedMsg
	}
	return nil
}

type Connect struct {
	FingerPrint          string   `protobuf:"bytes,1,opt,name=fingerPrint,proto3" json:"fingerPrint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{4}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetFingerPrint() string {
	if m != nil {
		return m.FingerPrint
	}
	return ""
}

type JoinSession struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TargetFingerPrint    string   `protobuf:"bytes,3,opt,name=targetFingerPrint,proto3" json:"targetFingerPrint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSession) Reset()         { *m = JoinSession{} }
func (m *JoinSession) String() string { return proto.CompactTextString(m) }
func (*JoinSession) ProtoMessage()    {}
func (*JoinSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{5}
}

func (m *JoinSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSession.Unmarshal(m, b)
}
func (m *JoinSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSession.Marshal(b, m, deterministic)
}
func (m *JoinSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSession.Merge(m, src)
}
func (m *JoinSession) XXX_Size() int {
	return xxx_messageInfo_JoinSession.Size(m)
}
func (m *JoinSession) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSession.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSession proto.InternalMessageInfo

func (m *JoinSession) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *JoinSession) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinSession) GetTargetFingerPrint() string {
	if m != nil {
		return m.TargetFingerPrint
	}
	return ""
}

type MsgReceipt struct {
	MsgId                string              `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	State                MsgReceipt_MsgState `protobuf:"varint,2,opt,name=state,proto3,enum=tmcs_msg.MsgReceipt_MsgState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MsgReceipt) Reset()         { *m = MsgReceipt{} }
func (m *MsgReceipt) String() string { return proto.CompactTextString(m) }
func (*MsgReceipt) ProtoMessage()    {}
func (*MsgReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c7e6332a77e25ed, []int{6}
}

func (m *MsgReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReceipt.Unmarshal(m, b)
}
func (m *MsgReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReceipt.Marshal(b, m, deterministic)
}
func (m *MsgReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReceipt.Merge(m, src)
}
func (m *MsgReceipt) XXX_Size() int {
	return xxx_messageInfo_MsgReceipt.Size(m)
}
func (m *MsgReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReceipt proto.InternalMessageInfo

func (m *MsgReceipt) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *MsgReceipt) GetState() MsgReceipt_MsgState {
	if m != nil {
		return m.State
	}
	return MsgReceipt_Lost
}

func init() {
	proto.RegisterEnum("tmcs_msg.SignedMsg_MsgType", SignedMsg_MsgType_name, SignedMsg_MsgType_value)
	proto.RegisterEnum("tmcs_msg.MsgReceipt_MsgState", MsgReceipt_MsgState_name, MsgReceipt_MsgState_value)
	proto.RegisterType((*NewSession)(nil), "tmcs_msg.NewSession")
	proto.RegisterType((*SignedMsg)(nil), "tmcs_msg.SignedMsg")
	proto.RegisterType((*MsgPackage)(nil), "tmcs_msg.MsgPackage")
	proto.RegisterType((*Message)(nil), "tmcs_msg.Message")
	proto.RegisterType((*Connect)(nil), "tmcs_msg.Connect")
	proto.RegisterType((*JoinSession)(nil), "tmcs_msg.JoinSession")
	proto.RegisterType((*MsgReceipt)(nil), "tmcs_msg.MsgReceipt")
}

func init() { proto.RegisterFile("tmcs_msg.proto", fileDescriptor_9c7e6332a77e25ed) }

var fileDescriptor_9c7e6332a77e25ed = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0xe1, 0x8a, 0x13, 0x31,
	0x10, 0x76, 0xaf, 0xed, 0x35, 0x9d, 0x96, 0xd2, 0x0b, 0x87, 0x2c, 0x8a, 0x70, 0xc4, 0x3f, 0x07,
	0x6a, 0x4f, 0x7a, 0x8f, 0x20, 0x08, 0x8a, 0xca, 0x91, 0x1e, 0xfe, 0x3d, 0xf6, 0x76, 0xe7, 0x96,
	0x50, 0x37, 0x59, 0x92, 0x54, 0xe9, 0x1b, 0xf8, 0x6a, 0xbe, 0x95, 0x93, 0x64, 0xbb, 0x56, 0xab,
	0xf8, 0x63, 0x21, 0xdf, 0xcc, 0x97, 0xcc, 0x37, 0xdf, 0xcc, 0xc2, 0xdc, 0x37, 0xa5, 0xbb, 0x6b,
	0x5c, 0xbd, 0x6c, 0xad, 0xf1, 0x86, 0xb3, 0x3d, 0x16, 0x9f, 0x01, 0x3e, 0xe1, 0xb7, 0x35, 0x3a,
	0xa7, 0x8c, 0xe6, 0x8f, 0xe1, 0xb4, 0xdd, 0xde, 0x6f, 0x70, 0x97, 0x67, 0x17, 0xd9, 0xe5, 0x44,
	0x76, 0x88, 0x3f, 0x01, 0xf6, 0x45, 0x3d, 0xe0, 0xad, 0x6a, 0x30, 0x3f, 0xa1, 0xcc, 0x40, 0xf6,
	0x98, 0x9f, 0xc3, 0xa8, 0xb6, 0x66, 0xdb, 0xe6, 0x03, 0x4a, 0x30, 0x99, 0x80, 0xf8, 0x91, 0xc1,
	0x64, 0xad, 0x6a, 0x8d, 0xd5, 0x47, 0x57, 0xf3, 0x1c, 0xc6, 0x0d, 0x95, 0x28, 0x6a, 0x8c, 0x0f,
	0xcf, 0xe4, 0x1e, 0xf2, 0x0b, 0x98, 0x3e, 0x28, 0x5d, 0xa3, 0xbd, 0xb1, 0x4a, 0xfb, 0xf8, 0xf8,
	0x44, 0x1e, 0x86, 0x82, 0x26, 0x87, 0xba, 0x42, 0x1b, 0x0b, 0x90, 0xa6, 0x84, 0x38, 0x87, 0xa1,
	0xa3, 0x02, 0xf9, 0x30, 0x46, 0xe3, 0x99, 0x5f, 0xc1, 0xd0, 0xef, 0x5a, 0xcc, 0x47, 0x14, 0x9b,
	0xaf, 0x9e, 0x2e, 0xfb, 0xb6, 0x7b, 0x29, 0x4b, 0xfa, 0x6e, 0x89, 0x22, 0x23, 0x51, 0x3c, 0x87,
	0x71, 0x17, 0xe0, 0x53, 0x3a, 0x26, 0x51, 0x8b, 0x47, 0x01, 0x48, 0x2c, 0x51, 0xb5, 0x7e, 0x91,
	0x89, 0x06, 0x80, 0x48, 0x37, 0x45, 0xb9, 0x09, 0x8a, 0x5f, 0x03, 0xb3, 0x29, 0xe5, 0xa8, 0x99,
	0xc1, 0xe5, 0x74, 0x75, 0xfe, 0xab, 0x0e, 0xf1, 0xba, 0x7b, 0xb2, 0x67, 0xf1, 0x57, 0xc0, 0xba,
	0x76, 0x1d, 0x35, 0x18, 0x6e, 0x9c, 0x1d, 0xdc, 0x48, 0x19, 0xd9, 0x53, 0xc4, 0x5d, 0x2f, 0x24,
	0x78, 0x4b, 0x9c, 0x77, 0x55, 0x37, 0x8e, 0x04, 0xc2, 0x34, 0xe2, 0xdb, 0x5f, 0xc9, 0x93, 0x64,
	0x58, 0x8f, 0xb9, 0x80, 0x19, 0xea, 0xd2, 0xee, 0x5a, 0x1f, 0xdb, 0x8d, 0x9e, 0xcd, 0xe4, 0x6f,
	0x31, 0xf1, 0x02, 0xc6, 0x6f, 0x8c, 0xd6, 0x58, 0xfa, 0x3f, 0xed, 0xcf, 0x8e, 0xec, 0x17, 0x0a,
	0xa6, 0xef, 0x8d, 0xd2, 0xff, 0xdb, 0x10, 0x52, 0xea, 0xcd, 0x06, 0x75, 0x27, 0x28, 0x01, 0xfe,
	0x12, 0xce, 0x7c, 0x61, 0x6b, 0xf4, 0x6f, 0x0f, 0x8a, 0xa4, 0x31, 0x1e, 0x27, 0xc4, 0xf7, 0x2c,
	0x1a, 0xdd, 0x19, 0xf8, 0x8f, 0xe6, 0xaf, 0x61, 0xe4, 0x7c, 0xe1, 0xd3, 0x1e, 0xce, 0x57, 0xcf,
	0xfe, 0xe6, 0x7d, 0x38, 0xae, 0x03, 0x49, 0x26, 0xae, 0xb8, 0x02, 0xb6, 0x0f, 0x71, 0x06, 0xc3,
	0x0f, 0xc6, 0x79, 0x1a, 0xf2, 0x0c, 0x98, 0x4c, 0xbe, 0x55, 0x8b, 0x2c, 0x8c, 0x3c, 0xec, 0xb3,
	0xd9, 0xfa, 0xc5, 0xc9, 0xfd, 0x69, 0xfc, 0x4f, 0xae, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x40,
	0x5d, 0xca, 0x37, 0x39, 0x03, 0x00, 0x00,
}
